### ISSUE TITLE
Add support for stackables

### ISSUE THREAD

**Issue by DesktopMan** [Algalish/SmartFoundationsPublic#23]
These would be great:

* Stackable Conveyor Pole
* Stackable Pipeline Support
* Stackable Hyper Tube Support

**Comment by Algalish** [comment]
@DesktopMan  I was thinking about it this week too. And you know what would be even better? Stackable belts! When you Have for example Stackable Conveyor Pole with the height of 5. and when you point to the lower pole and Shift+MouseWheel then you have all 5 belts ready to be built. Same with pipes. Because what is the point of building big Conveyor Poles if you can't build smart belts right?

**Comment by Algalish** [comment]
@DesktopMan  Implemented in V6
